services:
  backend:
    build:
      context: ./from-backend-fix2
      dockerfile: Dockerfile
    env_file:
      - ./from-backend-fix2/.env 
    ports:
      - "4002:4002"                
    volumes:
      - backend-storage:/app/storage 
      - ./from-backend-fix2/.env:/app/.env:ro
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:4002/up >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: ./from-frontend
      dockerfile: Dockerfile
    env_file:
      - ./from-frontend/.env         
    ports:
      - "4001:4001"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  backend-storage:
