# docker-compose.b.yml
version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./from-backend-fix2
      dockerfile: Dockerfile
      args:
        # ปรับได้ผ่าน .env หากต้องการ
        APT_MIRROR: ${APT_MIRROR:-deb.debian.org}
        PACKAGIST: ${PACKAGIST:-https://packagist.org}
        http_proxy:  ${HTTP_PROXY-}
        https_proxy: ${HTTPS_PROXY-}
        no_proxy:    ${NO_PROXY-}
    env_file: [ ./.env ]
    environment:
      TZ: ${TZ:-Asia/Bangkok}
      APP_ENV: ${APP_ENV:-local}
      APP_PORT: ${BACKEND_PORT}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-1}
      RUN_SEEDER: ${RUN_SEEDER:-1}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./from-backend-fix2/storage:/app/storage
      - ./from-backend-fix2/bootstrap/cache:/app/bootstrap/cache
      - ./.env:/app/.env:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [ app-net ]
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./from-frontend
      dockerfile: Dockerfile
    env_file: [ ./.env ]
    environment:
      TZ: ${TZ:-Asia/Bangkok}
      NODE_ENV: development
      PORT: ${FRONTEND_PORT}
    command: ["npm","run","dev","--","--port","${FRONTEND_PORT}","--hostname","0.0.0.0"]
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./from-frontend:/app
      - /app/node_modules
    depends_on: [ backend ]
    networks: [ app-net ]
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
