# docker-compose.yml (ไม่ใส่ version เพื่อเลี่ยงคำเตือน)
services:
  backend:
    build:
      context: ./from-backend-fix2
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_HOST_PORT}:${APP_PORT}"
    env_file: [ ./.env ]
    environment:
      RUN_MIGRATIONS: "${RUN_MIGRATIONS:-1}"
      RUN_SEEDER: "${RUN_SEEDER:-1}"
      TZ: ${TZ:-Asia/Bangkok}
    # อุ่นใจ: dump-autoload ก่อนเข้า entrypoint (กันกรณี seeder ยังไม่ถูก autoload)
    entrypoint:
      - /bin/sh
      - -lc
      - |
        set -e
        echo "[compose] composer dump-autoload -o ..."
        composer dump-autoload -o || true
        exec /usr/local/bin/entrypoint.sh
    networks: [app-network]

  frontend:
    build:
      context: ./from-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_USE_MOCK: "${NEXT_PUBLIC_USE_MOCK}"
        NEXT_PUBLIC_API_BASE_URL: "${BACKEND_URL}"
        NEXT_PUBLIC_BASE_URL: "${BACKEND_URL}"
        NEXT_PUBLIC_CARD_API: "${NEXT_PUBLIC_CARD_API}"
        NEXT_PUBLIC_PPK11_API: "${NEXT_PUBLIC_PPK11_API}"
        NEXT_PUBLIC_FORM_API: "${NEXT_PUBLIC_FORM_API}"
    container_name: frontend
    depends_on: [backend]
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_PORT}"
    environment:
      TZ: ${TZ:-Asia/Bangkok}
      PORT: "${FRONTEND_PORT}"
    networks: [app-network]

  # (ตัวเลือก) phpMyAdmin ต่อกับ MySQL บนเครื่องคุณ
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    env_file: [ ./.env ]
    environment:
      PMA_HOST: "host.docker.internal"
      PMA_PORT: "${DB_PORT}"
      PMA_ARBITRARY: "1"
    ports:
      - "${PMA_HOST_PORT}:80"
    networks: [app-network]

networks:
  app-network:
    driver: bridge
