services:
  backend:
    build:
      context: ./from-backend-fix2
      dockerfile: Dockerfile
    env_file:
      - ./from-backend-fix2/.env.backend     # ต้องมี APP_PORT=4002, DB, APP_KEY
    environment:
      TZ: Asia/Bangkok
    ports:
      - "4002:4002"
    volumes:
      - ./from-backend-fix2/storage:/app/storage
      - ./from-backend-fix2/.env.backend:/app/.env:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [ app-net ]
    restart: unless-stopped

  frontend:
    build:
      context: ./from-frontend
      dockerfile: Dockerfile
    env_file:
      - ./from-frontend/.env.frontend        # ต้องมี PORT=4001 และ NEXT_PUBLIC_*
    environment:
      NODE_ENV: production
      TZ: Asia/Bangkok
    ports:
      - "4001:4001"
    depends_on: [ backend ]
    networks: [ app-net ]
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
