version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fenyb1
      MYSQL_PASSWORD: 0959611859fenyb1
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [app-network]

  backend:
    build:
      context: ./from-backend-fix2
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9001:9001"   # ← ใช้พอร์ตที่ต้องการ
    volumes:
      - ./from-backend-fix2:/app
    env_file:
      - ./from-backend-fix2/.env
    environment:
      TZ: Asia/Bangkok
      # (ทางเลือก) ระบุ seeder หลักที่อยากรัน (นอกเหนือจาก DatabaseSeeder)
      # SEED_CLASS=AdminUserSeeder
    networks: [app-network]

  frontend:
    build:
      context: ./from-frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on: [backend]
    ports:
      - "3000:3000"
    volumes:
      - ./from-frontend:/app
      - /app/node_modules
    env_file:
      - ./from-frontend/.env
    environment:
      TZ: Asia/Bangkok
    networks: [app-network]

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
